version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-197-48-79.compute-1.amazonaws.com
            port: '5432'
            database: d9b5b69m50fu03
            ssl: true
            user: dbvacnuwjpwnst
            password: 8a1b11bdcf74336e801b6286f4ab51dde5e025dbdc1d24b4f9924a2f2f9d7712
            migrations: true